### ISSUE TITLE
VLP 16 data convert

### ISSUE THREAD

**Issue by minghaohsu410168** [mihsamusev/pylidarlib#1]
Hello, 

Can this repo convert the pcap collected with VLP 16?
And how do you label the object class "Car", "Pedestrian" like KITTI format?

Thank you

**Comment by mihsamusev** [comment]
Hi,
1) This repo atm only supports parsing of HDL32e because that`s the only Lidar we have at work, but maybe you can look at pylidarlib.io.HDL32e to see how its done and adapt the code for VLP16 by substituting constants for pack size, block size, laser elevations, etc from VLP16 data sheet. if you do, would be cool to get a pull request.
2) This repo does not deal with labels, it is meant solely for transforming point clouds
